<?php

return [
    'disk' => env('MUNICIPAL_DATA_DISK', 'local'),
    'artifact_path' => env('MUNICIPAL_DATA_ARTIFACT_PATH', 'municipal-data/sources'),
    'http' => [
        'timeout_seconds' => (int) env('MUNICIPAL_DATA_HTTP_TIMEOUT', 30),
        'connect_timeout_seconds' => (int) env('MUNICIPAL_DATA_HTTP_CONNECT_TIMEOUT', 10),
        'retry_times' => (int) env('MUNICIPAL_DATA_HTTP_RETRIES', 3),
        'retry_sleep_milliseconds' => (int) env('MUNICIPAL_DATA_HTTP_RETRY_SLEEP', 500),
    ],
    'sources' => [
        'ibge_localities_url' => 'https://servicodados.ibge.gov.br/api/v1/localidades/municipios?orderBy=nome',
    ],
    'population' => [
        2017 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/6579/n6/all/v/9324/p/2017?formato=json',
            'format' => 'json',
            'methodology' => 'ibge_population_estimate',
            'statistical_reference_date' => '2017-07-01',
            'territorial_reference' => '2017',
            'published_at' => '2024-06-24',
            'expected_records' => 5571,
            'expected_available_municipalities' => 5570,
            'dataset' => 'SIDRA 6579 / variável 9324',
        ],
        2020 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/6579/n6/all/v/9324/p/2020?formato=json',
            'format' => 'json',
            'methodology' => 'ibge_population_estimate',
            'statistical_reference_date' => '2020-07-01',
            'territorial_reference' => '2020',
            'published_at' => '2024-06-24',
            'expected_records' => 5571,
            'expected_available_municipalities' => 5570,
            'dataset' => 'SIDRA 6579 / variável 9324',
        ],
        2021 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/6579/n6/all/v/9324/p/2021?formato=json',
            'format' => 'json',
            'methodology' => 'ibge_population_estimate',
            'statistical_reference_date' => '2021-07-01',
            'territorial_reference' => '2021',
            'published_at' => '2024-06-24',
            'expected_records' => 5571,
            'expected_available_municipalities' => 5570,
            'dataset' => 'SIDRA 6579 / variável 9324',
        ],
        2022 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/4709/n6/all/v/93/p/2022?formato=json',
            'format' => 'json',
            'methodology' => 'census_population',
            'statistical_reference_date' => '2022-07-31',
            'territorial_reference' => '2022',
            'published_at' => '2023-12-22',
            'expected_records' => 5570,
            'expected_available_municipalities' => 5570,
            'dataset' => 'SIDRA 4709 / variável 93',
        ],
        2023 => [
            'url' => 'https://ftp.ibge.gov.br/Informacoes_Gerais_e_Referencia/Relacao_da_Populacao_dos_Municipios_para_publicacao_no_DOU_em_2023/POP_TCU_2023_Municipios_POP2022_Malha2023.ods',
            'format' => 'ods',
            'methodology' => 'official_tcu_population_reference',
            'statistical_reference_date' => '2022-07-31',
            'territorial_reference' => 'Malha 2023',
            'published_at' => '2024-02-23',
            'expected_records' => 5570,
            'expected_available_municipalities' => 5570,
            'dataset' => 'POP TCU 2023 — Censo 2022 e Malha 2023',
        ],
        2024 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/6579/n6/all/v/9324/p/2024?formato=json',
            'format' => 'json',
            'methodology' => 'ibge_population_estimate',
            'statistical_reference_date' => '2024-07-01',
            'territorial_reference' => '2024',
            'published_at' => '2024-12-30',
            'expected_records' => 5571,
            'expected_available_municipalities' => 5570,
            'dataset' => 'SIDRA 6579 / variável 9324',
        ],
        2025 => [
            'url' => 'https://apisidra.ibge.gov.br/values/t/6579/n6/all/v/9324/p/2025?formato=json',
            'format' => 'json',
            'methodology' => 'ibge_population_estimate',
            'statistical_reference_date' => '2025-07-01',
            'territorial_reference' => '2025',
            'published_at' => '2026-01-13',
            'expected_records' => 5571,
            'expected_available_municipalities' => 5571,
            'dataset' => 'SIDRA 6579 / variável 9324',
        ],
    ],
    'homicides' => [
        'url' => 'http://tabnet.datasus.gov.br/cgi/tabcgi.exe?sim/cnv/obt10br.def',
        'methodology_url' => 'https://www.ipea.gov.br/atlasviolencia/pg/26/perguntas-frequentes',
        'definition' => 'CID-10 X85-Y09 e Y35-Y36, por município de residência',
        'available_through' => 2024,
        'unavailable_note' => 'O SIM não publicou dados municipais definitivos ou preliminares para este exercício.',
        'years' => [
            2017 => ['file' => 'obtbr17.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
            2020 => ['file' => 'obtbr20.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
            2021 => ['file' => 'obtbr21.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
            2022 => ['file' => 'obtbr22.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
            2023 => ['file' => 'obtbr23.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
            2024 => ['file' => 'obtbr24.dbf', 'published_at' => '2025-12-02', 'expected_municipalities' => 5570],
        ],
    ],
    'gdp' => [
        'url' => 'https://ftp.ibge.gov.br/Pib_Municipios/2022_2023/base/base_de_dados_2010_2023_txt.zip',
        'entry' => 'PIB dos Municípios - base de dados 2010-2023.txt',
        'methodology_url' => 'https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9088-produto-interno-bruto-dos-municipios.html',
        'available_through' => 2023,
        'unavailable_note' => 'O IBGE ainda não publicou o PIB municipal para este exercício.',
        'years' => [
            2017 => ['published_at' => '2025-12-19', 'expected_municipalities' => 5570],
            2020 => ['published_at' => '2025-12-19', 'expected_municipalities' => 5570],
            2021 => ['published_at' => '2025-12-19', 'expected_municipalities' => 5570],
            2022 => ['published_at' => '2025-12-19', 'expected_municipalities' => 5570],
            2023 => ['published_at' => '2025-12-19', 'expected_municipalities' => 5570],
        ],
    ],
    'census_indicators' => [
        'reference_year' => 2022,
        'published_at' => '2024-05-17',
        'expected_municipalities' => 5570,
        'datasets' => [
            'water_census' => [
                'url' => 'https://apisidra.ibge.gov.br/values/t/6803/n6/all/v/1000381/p/2022/c1821/72144?formato=json',
                'entry' => 'water_census.json',
                'table' => 6803,
                'category_code' => 72144,
                'definition' => 'Percentual de domicílios particulares permanentes ocupados que possuem ligação à rede geral e a utilizam como forma principal.',
                'updated_at' => '2024-02-23',
            ],
            'sewer_census' => [
                'url' => 'https://apisidra.ibge.gov.br/values/t/6805/n6/all/v/1000381/p/2022/c11558/46290?formato=json',
                'entry' => 'sewer_census.json',
                'table' => 6805,
                'category_code' => 46290,
                'definition' => 'Percentual de domicílios particulares permanentes ocupados com rede geral, rede pluvial ou fossa ligada à rede.',
                'updated_at' => '2024-02-23',
            ],
            'literacy_rate' => [
                'url' => 'https://apisidra.ibge.gov.br/values/t/9543/n6/all/v/2513/p/2022?formato=json',
                'entry' => 'literacy_rate.json',
                'table' => 9543,
                'category_code' => 'total_15_or_older',
                'definition' => 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade.',
                'updated_at' => '2024-05-17',
            ],
        ],
    ],
    'sinisa' => [
        'reference_year' => 2023,
        'published_at' => '2025-10-16',
        'available_through' => 2023,
        'unavailable_note' => 'O SINISA ainda não publicou as planilhas finais auditadas para este exercício.',
        'expected_municipalities' => 5570,
        'results_url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/resultados-sinisa/resultados-sinisa',
        'datasets' => [
            'water_service_coverage' => [
                'indicator_code' => 'IAG0001',
                'definition' => 'Atendimento da população total com rede de abastecimento de água.',
                'url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/arquivos/SINISA_Resultados_Ref2023.zip',
                'local_path' => env('MUNICIPAL_DATA_SINISA_WATER_FILE'),
                'sha256' => '1af66e823f534d5f2e513de5c4484cf5c12e8feb727ae602427af1a559bf9fea',
                'wrapper_entry' => 'sinisa_water_2023.zip',
                'xlsx_entry' => 'SINISA_Resultados_Ref2023/Água - Base Municipal/SINISA_AGUA_Indicadores_Base Municipal_2023.xlsx',
                'expected_source_rows' => 5241,
            ],
            'sewer_service_coverage' => [
                'indicator_code' => 'IES0001',
                'definition' => 'Atendimento da população total com rede coletora de esgoto.',
                'url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/resultados-sinisa/SINISA_ESGOTO_Planilhas_2023_v2.zip?download=1',
                'local_path' => env('MUNICIPAL_DATA_SINISA_SEWER_FILE'),
                'sha256' => '2ae2b09d8bc892ec1013ae91e5352deb9ee80611499b91bcc6309f6fc0d8b1e6',
                'wrapper_entry' => 'sinisa_sewer_2023.zip',
                'xlsx_entry' => 'Esgoto - Base Municipal/SINISA_ESGOTO_Indicadores_Base Municipal_2023_V2.xlsx',
                'expected_source_rows' => 2754,
                'corrections' => [
                    [
                        'url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/arquivos/SINISA_ESGOTO_Indicadores_Prestadoreslocaiseregionais_2023_Retificacao1.xlsx',
                        'local_path' => env('MUNICIPAL_DATA_SINISA_SEWER_CORRECTION_1_FILE'),
                        'sha256' => '2cbd24816a131a2e96ab582c73f69ca54b252224e1534e67da096c765ba25caf',
                        'wrapper_entry' => 'sinisa_sewer_correction_1.xlsx',
                        'expected_source_rows' => 2,
                    ],
                    [
                        'url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/arquivos/SINISA_ESGOTO_Indicadores_Prestadoreslocaiseregionais_2023_RetificacaoV2.xlsx',
                        'local_path' => env('MUNICIPAL_DATA_SINISA_SEWER_CORRECTION_2_FILE'),
                        'sha256' => '312a76348cdca9dfb6f74ad4d8540618974d9d8f65a603706fd4280bbe4f17b5',
                        'wrapper_entry' => 'sinisa_sewer_correction_2.xlsx',
                        'expected_source_rows' => 1,
                    ],
                    [
                        'url' => 'https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/sinisa/arquivos/SINISA_ESGOTO_Indicadores_Prestadoreslocaiseregionais_2023_Retificacao_Para_de_Minas.xlsx',
                        'local_path' => env('MUNICIPAL_DATA_SINISA_SEWER_CORRECTION_3_FILE'),
                        'sha256' => 'd595b33041e160268dee545bedde25dced3883564424c223a08f4bc199ea5cdc',
                        'wrapper_entry' => 'sinisa_sewer_correction_3.xlsx',
                        'expected_source_rows' => 1,
                    ],
                ],
            ],
        ],
    ],
    'ideb' => [
        'published_at' => '2025-01-07',
        'available_through' => 2023,
        'unavailable_note' => 'O INEP ainda não publicou o IDEB municipal de 2025.',
        'expected_municipalities' => 5570,
        'cycles' => [2017, 2019, 2021, 2023],
        'datasets' => [
            'ideb_initial_years' => [
                'url' => 'https://download.inep.gov.br/ideb/resultados/divulgacao_anos_iniciais_municipios_2023.zip',
                'local_path' => env('MUNICIPAL_DATA_IDEB_INITIAL_FILE'),
                'sha256' => '866c50e858e5f4d3d0b7b380c3adc05b56f6137360d7830e23dae72284e8c9f4',
                'wrapper_entry' => 'ideb_initial_years.zip',
                'xlsx_entry' => 'divulgacao_anos_iniciais_municipios_2023/divulgacao_anos_iniciais_municipios_2023.xlsx',
                'expected_source_rows' => 5433,
                'stage' => 'Ensino Fundamental Regular - Anos Iniciais',
            ],
            'ideb_final_years' => [
                'url' => 'https://download.inep.gov.br/ideb/resultados/divulgacao_anos_finais_municipios_2023.zip',
                'local_path' => env('MUNICIPAL_DATA_IDEB_FINAL_FILE'),
                'sha256' => 'bb3b7d8a176e89f1208c6277fceed2a79724c04c11513ef5ce083fb44a861986',
                'wrapper_entry' => 'ideb_final_years.zip',
                'xlsx_entry' => 'divulgacao_anos_finais_municipios_2023/divulgacao_anos_finais_municipios_2023.xlsx',
                'expected_source_rows' => 3906,
                'stage' => 'Ensino Fundamental Regular - Anos Finais',
            ],
        ],
    ],
    'tse' => [
        'municipality_codes' => [
            'url' => 'https://cdn.tse.jus.br/estatistica/sead/odsele/municipio_tse_ibge/municipio_tse_ibge.zip',
            'local_path' => env('MUNICIPAL_DATA_TSE_CODES_FILE'),
            'published_at' => '2025-06-24',
        ],
        'elections' => [
            2016 => [
                'url' => 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2016.zip',
                'local_path' => env('MUNICIPAL_DATA_TSE_CANDIDATES_2016_FILE'),
                'published_at' => '2021-08-23',
            ],
            2020 => [
                'url' => 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2020.zip',
                'local_path' => env('MUNICIPAL_DATA_TSE_CANDIDATES_2020_FILE'),
                'published_at' => '2021-08-05',
            ],
            2024 => [
                'url' => 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2024.zip',
                'local_path' => env('MUNICIPAL_DATA_TSE_CANDIDATES_2024_FILE'),
                'published_at' => '2024-07-19',
            ],
        ],
    ],
];
